<?php

namespace App\Http\Controllers\Modules;

use App\Http\Controllers\Controller;

class Map extends Controller
{
    public function mapId(): array
    {
        return [
            1 => "Port Akaba",
            2 => "Red Rock",
            3 => "Library",
            4 => "M Station",
            5 => "Midnight Zone",
            6 => "Uptown",
            7 => "Burning Hall",
            8 => "D Squad",
            9 => "Crackdown",
            10 => "Saint Mansion",
            11 => "Eastern Road",
            12 => "Downtown",
            13 => "Luxville",
            14 => "Blowcity",
            15 => "Stormtube",
            17 => "Breakdown",
            18 => "Training Camp",
            19 => "Sentry Base",
            20 => "Mini Indonesia",
            21 => "Kick Point",
            22 => "Face Rock",
            23 => "Supply Base",
            24 => "Sand Storm",
            25 => "Downtown",
            26 => "Luxville",
            27 => "Outpost",
            28 => "Blowcity",
            29 => "Stormtube",
            30 => "Sentry Base",
            31 => "Hospital",
            32 => "Midtown",
            33 => "Shopping Center",
            34 => "Sand Storm",
            35 => "Breakdown",
            38 => "Helispot",
            39 => "Black Panther",
            40 => "Breeding Nest",
            41 => "Dino Uptown",
            42 => "Dino Breakdown",
            45 => "Shopping Center",
            46 => "Safari",
            47 => "Dragon Alley",
            48 => "Machu Pichu",
            49 => "Cargoship",
            50 => "Two Towers",
            51 => "Crackdown",
            52 => "Saint Mansion",
            53 => "D Squad",
            54 => "Port Akaba",
            55 => "M Station",
            56 => "Training Camp",
            57 => "Angkor Ruins",
            58 => "Red Rock",
            59 => "Safari",
            60 => "Ghost Town",
            61 => "Grand Bazaar",
            62 => "Dino Lab",
            63 => "Under 23",
            64 => "Taipei City Mall",
            65 => "Safari 2",
            66 => "Airport",
            67 => "Safari 2",
            68 => "Metro",
            77 => "Rush Hour",
            78 => "Cargo Port",
            79 => "Black Mamba",
            80 => "Safe House",
            82 => "West Station",
            83 => "Hard Rock",
            84 => "The Museum",
            85 => "Pumpkin Hollow",
            86 => "Rothen Village",
            88 => "Water Complex",
            89 => "Hotel Camouflage",
            90 => "Battle Ship",
            92 => "Ballistic",
            93 => "Rampart Town",
            94 => "Fallu City",
            98 => "Hindrance",
            99 => "Sewerage",
            100 => "Slum Area",
            101 => "Library 2",
            102 => "Sand Storm",
            103 => "Dino Ruins",
            104 => "Fatal Zone",
            105 => "Marine Wave",
            106 => "Still Raid",
            107 => "Old Dock",
            108 => "Biolab",
            109 => "Jembatan Ampera",
            110 => "Mihawk",
            111 => "Broken Alley",
            112 => "Provence",
            113 => "Zombie Bridge",
            114 => "Mihawk",
            115 => "Thai Stadium",
            116 => "Roadside",
            117 => "Zombie Airport",
            118 => "Junkyard",
            119 => "Fort Santiago",
            120 => "Crackdown 2",
            121 => "Hospital",
            122 => "Octagon"
        ];
    }

    public function mapStage(): array
    {
        return [
            109 => 'Deathmatch',
            33 => 'Destruction',
            38 => 'Sabotage',
            1 => 'Supression',
            39 => 'Defense',
            1 => 'Challenge',
            40 => 'Dinosauro',
            1 => 'Sniper',
            2 => 'Shotgun',
            1 => 'HeadHunter',
            1 => 'Knuckle',
            62 => 'Cross-Counter',
            1 => 'Chaos',
            106 => 'ThiefMode'
        ];
    }
}
